/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Add answer request
 */
export interface ReqAddAnswer { 
    /**
     * The id of the unit content
     */
    unitContentId: number;
    /**
     * The success of the result of the translation
     */
    right: boolean;
    /**
     * The interrogation type. Currently just the WRITING, SELF_DECLARATION enabled
     */
    interrogationType: ReqAddAnswer.InterrogationTypeEnum;
    /**
     * The id of the from language (the from-to can be changed)
     */
    fromLanguageId: number;
}
export namespace ReqAddAnswer {
    export type InterrogationTypeEnum = 'WRITING' | 'SELF_DECLARATION';
    export const InterrogationTypeEnum = {
        Writing: 'WRITING' as InterrogationTypeEnum,
        SelfDeclaration: 'SELF_DECLARATION' as InterrogationTypeEnum
    };
}


