/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Translation save request
 */
export interface ReqTranslationSave { 
    /**
     * The unit id
     */
    id: number;
    /**
     * The example sentence for the phrase
     */
    example?: string;
    /**
     * The translated example sentence for the phrase
     */
    translatedExample?: string;
    /**
     * The from language phrases
     */
    from: Array<string>;
    /**
     * The to language phrases
     */
    to: Array<string>;
}

