/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Word type unit link
 */
export interface ReqWordTypeUnitLink { 
    /**
     * The id of the word type unit
     */
    wordTypeUnitId: number;
    /**
     * The id of the word type link (word type translation)
     */
    wordTypeLinkId: number;
}

