/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TranslationForPhrase } from './translationForPhrase';


export interface ResPhrasesForUnitAllOf { 
    /**
     * The translations of the unit with example and calculated interrogation time
     */
    words?: Array<TranslationForPhrase>;
}

