/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Translation } from './translation';


/**
 * The unit with the translations
 */
export interface ResTranslationsForUnit { 
    /**
     * The name of the unit leaf
     */
    name: string;
    /**
     * The id of the unit leaf
     */
    code: number;
    /**
     * The translations of the unit with example and calculated interrogation time
     */
    translations?: Array<Translation>;
}

