/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResWordTypeTranslationRowsInner } from './resWordTypeTranslationRowsInner';
import { WordTypeUnit } from './wordTypeUnit';


/**
 * Word type translation response
 */
export interface ResWordTypeTranslation { 
    /**
     * The name of the word type
     */
    name: string;
    /**
     * The translation data for the word from-to words and the connection to the unit
     */
    rows?: Array<ResWordTypeTranslationRowsInner>;
    /**
     * The defined forms of the word type
     */
    forms: Array<string>;
    /**
     * It is a list of the available unit for the word types, for which the words are connected/linked
     */
    wordTypeUnits: Array<WordTypeUnit>;
}

