/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WordTypeTranslation } from './wordTypeTranslation';


/**
 * Word type unit translation response
 */
export interface ResWordTypeUnitTranslation { 
    /**
     * The name of the word type
     */
    name: string;
    /**
     * The defined forms of the word type
     */
    forms: Array<string>;
    rows?: Array<WordTypeTranslation>;
}

