/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The translation extended with the interrogation data and unit content id
 */
export interface UserTranslation { 
    /**
     * The id of the unit content
     */
    unitContentId: number;
    /**
     * The time when the translation will be interrogated
     */
    nextInterrogationTime?: string;
    /**
     * The last time when the translation was answered
     */
    lastAnswerTime?: string;
    /**
     * The last answer was right
     */
    lastAnswerRight?: boolean;
}

