/**
 * Interrogator API 1.0
 * This is the Interrogator API for the web client Source: - [GitHub](https://github.com/ataastar/interrogator-api)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ata.astar@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The word type link translation data
 */
export interface WordTypeTranslation { 
    /**
     * The id of the word type link (translation)
     */
    id: number;
    toPhrases: Array<{ [key: string]: Array<string>; }>;
    fromPhrases: Array<string>;
}

